version: "3.9"
services:
  create-beacon-chain-genesis:
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl:latest"
    command:
      - testnet
      - generate-genesis
      - --fork=bellatrix
      - --num-validators=1
      - --output-ssz=/consensus/genesis.ssz
      - --chain-config-file=/consensus/config.yml
      - --geth-genesis-json-in=/execution/genesis.json
      - --geth-genesis-json-out=/execution/genesis.json
    volumes:
      - ./consensus:/consensus
      - ./execution:/execution

  geth-genesis:
    image: "ethereum/client-go:latest"
    command: --datadir=/execution init /execution/genesis.json
    volumes:
      - ./execution:/execution
      - ./execution/genesis.json:/execution/genesis.json
    depends_on:
      create-beacon-chain-genesis:
        condition: service_completed_successfully

  geth:
    image: "ethereum/client-go:latest"
    command:
      - --http
      - --http.api=personal,eth,net,web3
      - --http.addr=0.0.0.0
      - --http.corsdomain=*
      - --authrpc.vhosts=*
      - --authrpc.addr=0.0.0.0
      - --authrpc.jwtsecret=/execution/jwtsecret
      - --datadir=/execution
      - --allow-insecure-unlock
      - --unlock=0x123463a4b065722e99115d6c222f267d9cabb524
      - --password=/execution/geth_password.txt
      - --nodiscover
      - --syncmode=full
    ports:
      - 8551:8551
      - 8545:8545
    depends_on:
      geth-genesis:
        condition: service_completed_successfully
    volumes:
      - ./execution:/execution
      - ./execution/geth_password.txt:/execution/geth_password.txt
      - ./jwtsecret:/execution/jwtsecret

  beacon-chain:
    image: "gcr.io/prysmaticlabs/prysm/beacon-chain:latest"
    command:
      - --datadir=/consensus/beacondata
      - --min-sync-peers=0
      - --genesis-state=/consensus/genesis.ssz
      - --bootstrap-node=
      - --chain-config-file=/consensus/config.yml
      - --chain-id=${CHAIN_ID:-32382}
      - --rpc-host=0.0.0.0
      - --contract-deployment-block=0
      - --grpc-gateway-host=0.0.0.0
      - --execution-endpoint=http://geth:8551
      - --accept-terms-of-use
      - --jwt-secret=/execution/jwtsecret
      - --suggested-fee-recipient=0x123463a4b065722e99115d6c222f267d9cabb524
    depends_on:
      geth:
        condition: service_started
      create-beacon-chain-genesis:
        condition: service_completed_successfully
    ports:
      - 4000:4000
      - 3500:3500
      - 8080:8080
    volumes:
      - ./consensus:/consensus
      - ./jwtsecret:/execution/jwtsecret

  validator-keystore:
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"
    command: accounts import --keys-dir=/consensus/validator_keys --wallet-dir=/consensus/wallet --wallet-password-file=/consensus/pwd.txt --account-password-file=/consensus/pwd.txt --accept-terms-of-use
    volumes:
      - ./consensus:/consensus
      - ./consensus/wallet:/consensus/wallet
      - ./consensus/validator_keys:/consensus/validator_keys

  validator:
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"
    command:
      - --beacon-rpc-provider=beacon-chain:4000
      - --datadir=/consensus/validatordata
      - --wallet-password-file=/consensus/pwd.txt
      - --accept-terms-of-use
      - --interop-num-validators=1
      - --interop-start-index=0
      - --chain-config-file=/consensus/config.yml
    depends_on:
      beacon-chain:
        condition: service_started
    volumes:
      - ./consensus:/consensus
      - ./consensus/validator_keys:/consensus/validator_keys

  validatorcustom:
    image: "gcr.io/prysmaticlabs/prysm/validator:latest"
    command:
      - --beacon-rpc-provider=beacon-chain:4000
      - --datadir=/consensus/validatordata_custom
      - --wallet-dir=/consensus/wallet
      - --wallet-password-file=/consensus/pwd.txt
      - --accept-terms-of-use
      - --chain-config-file=/consensus/config.yml
    depends_on:
      beacon-chain:
        condition: service_started
      validator-keystore:
        condition: service_completed_successfully
    volumes:
      - ./consensus:/consensus
      - ./consensus/wallet:/consensus/wallet
      - ./consensus/validator_keys:/consensus/validator_keys
